version: '2'
volumes:
  npm-cache:
    driver: "local"
services:
  app:
    image: node:14.17.3-buster
    command: bash -c "npm run serve"
    working_dir: /var/www/html
    volumes:
      - ./apps/app:/var/www/html
      - npm-cache:/root/.npm
    ports:
      - "8080:8080"
